### ISSUE TITLE
CppInterOp doesn't find stddef.h

### ISSUE THREAD

**Issue by maleadt** [Gnimuc/CppInterOp.jl#1]
It may be a little early for filing issues, so stop me if I should just wait, but I encountered the following when testing the `basic` example:

```
julia> Cpp.Declare("""
       #include <iostream>
       #include <vector>
       """)
In file included from <<< inputs >>>:1:
In file included from input_line_2:1:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/iostream:41:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/ostream:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/ios:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/iosfwd:42:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/postypes.h:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/cwchar:44:
/usr/include/wchar.h:35:10: fatal error: 'stddef.h' file not found
   35 | #include <stddef.h>
      |          ^~~~~~~~~~
```

Relevant copies of `stddef.h` on my system (Arch Linux) are in:
```
/usr/include/linux/stddef.h
/usr/lib/clang/17/include/stddef.h
/usr/lib/gcc/x86_64-pc-linux-gnu/13.3.0/include/stddef.h
```

**Comment by Gnimuc** [comment]
Configuring a JLL-compatible-binary-build environment is tricky(see how we did in [Clang.jl](https://github.com/JuliaInterop/Clang.jl/blob/master/src/platform/system.jl)). I'm still working on it. 

If you want to play with it a bit, you can pass `-v` to `Cpp.CreateInterpreter(["-v"])` to get the list of wrong search paths the compiler used.

**Comment by Gnimuc** [comment]
@maleadt  This should be fixed now. But the Linux CI keeps failing...

https://github.com/Gnimuc/CppInterOp.jl/actions/runs/9367490416/job/25787279012#step:9:141

**Comment by maleadt** [comment]
Thanks, I'll try this out.

I guess the goal would be do redistribute necessary headers as a JLL instead of picking them up from the system? Especially for use on Windows.

**Comment by maleadt** [comment]
> But the Linux CI keeps failing...
> 
> https://github.com/Gnimuc/CppInterOp.jl/actions/runs/9367490416/job/25787279012#step:9:141

`Symbols not found: [ llvm_orc_registerEHFrameSectionWrapper ]`

That's LLVM being broken: https://github.com/llvm/llvm-project/issues/74671
Also see https://github.com/maleadt/LLVM.jl/issues/405. I haven't found a workaround...

**Comment by maleadt** [comment]
Thanks, the issue reported here is fixed. It "just" triggers the ORC bug now:

```
julia> Cpp.Declare("#include <iostream>")
Failed to execute via ::process:Symbols not found: [ llvm_orc_registerEHFrameSectionWrapper ]
1

julia> Cpp.Process("""std::cout << 42 << std::endl;""")
Failed to execute via ::process:Symbols not found: [ llvm_orc_registerEHFrameSectionWrapper ]
1
```
